import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/layout/Header";
import localFont from "next/font/local";

const specialFont = localFont({
  src: [
    {
      path: "../lib/fonts/Kamikaze/Kamikaze.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-special"
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${specialFont.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
