import type { Metadata } from "next";
import { Nunito, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/layout/Header";
import localFont from "next/font/local";
import { AuthProvider } from "@/contexts/AuthContex";

const specialFont = localFont({
  src: [
    {
      path: "../lib/fonts/Kamikaze/Kamikaze.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-special"
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${nunito.variable} ${geistMono.variable} ${specialFont.variable} antialiased`}
        >
          <Header />
          
          <div className="flex justify-center w-full">
            {children}
          </div>
        </body>        
      </AuthProvider>
    </html>
  );
}
