export const OFFICIAL_TAGS = [
  // ===== Diet & Lifestyle =====
  { key: "vegan", emoji: "🌱" },
  { key: "vegetarian", emoji: "🥬" },
  { key: "gluten_free", emoji: "🌾" },
  { key: "dairy_free", emoji: "🥛" },
  { key: "low_carb", emoji: "📉" },
  { key: "keto", emoji: "🥑" },
  { key: "high_protein", emoji: "💪" },
  { key: "paleo", emoji: "🦴" },
  { key: "sugar_free", emoji: "🚫" },
  { key: "healthy", emoji: "💚" },
  { key: "low_fat", emoji: "🪶" },
  { key: "whole30", emoji: "✅" },
  { key: "low_sodium", emoji: "🧂" },
  { key: "high_fiber", emoji: "🌿" },
  { key: "low_calorie", emoji: "⚖️" },
  { key: "fodmap", emoji: "🫃" },
  { key: "nut_free", emoji: "🥜" },
  { key: "egg_free", emoji: "🥚" },
  { key: "soy_free", emoji: "🫛" },
  { key: "halal", emoji: "☪️" },
  { key: "kosher", emoji: "✡️" },

  // ===== Protein Sources =====
  { key: "chicken", emoji: "🐔" },
  { key: "beef", emoji: "🥩" },
  { key: "pork", emoji: "🐷" },
  { key: "lamb", emoji: "🐑" },
  { key: "fish", emoji: "🐟" },
  { key: "seafood", emoji: "🦐" },
  { key: "turkey", emoji: "🦃" },
  { key: "duck", emoji: "🦆" },
  { key: "eggs", emoji: "🥚" },
  { key: "tofu", emoji: "🧈" },
  { key: "legumes", emoji: "🫘" },
  { key: "salmon", emoji: "🐟" },
  { key: "tuna", emoji: "🐟" },
  { key: "shrimp", emoji: "🦐" },
  { key: "crab", emoji: "🦀" },
  { key: "lobster", emoji: "🦞" },
  { key: "mussels", emoji: "🦪" },
  { key: "bacon", emoji: "🥓" },
  { key: "sausage", emoji: "🌭" },
  { key: "ground_meat", emoji: "🍖" },
  { key: "steak", emoji: "🥩" },
  { key: "tempeh", emoji: "🧱" },
  { key: "seitan", emoji: "🌾" },
  { key: "game", emoji: "🦌" },
  { key: "rabbit", emoji: "🐇" },

  // ===== Carbs & Starch =====
  { key: "pasta", emoji: "🍝" },
  { key: "rice", emoji: "🍚" },
  { key: "potato", emoji: "🥔" },
  { key: "noodles", emoji: "🍜" },
  { key: "bread", emoji: "🍞" },
  { key: "quinoa", emoji: "🌿" },
  { key: "couscous", emoji: "🥣" },
  { key: "sweet_potato", emoji: "🍠" },
  { key: "oats", emoji: "🥣" },
  { key: "polenta", emoji: "🌽" },
  { key: "bulgur", emoji: "🌾" },
  { key: "barley", emoji: "🌾" },
  { key: "farro", emoji: "🌾" },
  { key: "gnocchi", emoji: "🥟" },
  { key: "tortilla", emoji: "🫓" },
  { key: "pita", emoji: "🫓" },
  { key: "naan", emoji: "🫓" },
  { key: "croissant", emoji: "🥐" },
  { key: "bagel", emoji: "🥯" },

  // ===== Vegetables =====
  { key: "mushroom", emoji: "🍄" },
  { key: "tomato", emoji: "🍅" },
  { key: "onion", emoji: "🧅" },
  { key: "garlic", emoji: "🧄" },
  { key: "pepper", emoji: "🫑" },
  { key: "carrot", emoji: "🥕" },
  { key: "broccoli", emoji: "🥦" },
  { key: "spinach", emoji: "🥬" },
  { key: "zucchini", emoji: "🥒" },
  { key: "eggplant", emoji: "🍆" },
  { key: "cauliflower", emoji: "🥦" },
  { key: "cabbage", emoji: "🥬" },
  { key: "corn", emoji: "🌽" },
  { key: "pumpkin", emoji: "🎃" },
  { key: "squash", emoji: "🎃" },
  { key: "asparagus", emoji: "🥬" },
  { key: "avocado", emoji: "🥑" },
  { key: "cucumber", emoji: "🥒" },
  { key: "kale", emoji: "🥬" },
  { key: "beets", emoji: "🫒" },
  { key: "leek", emoji: "🥬" },
  { key: "celery", emoji: "🥬" },

  // ===== Fruits =====
  { key: "apple", emoji: "🍎" },
  { key: "banana", emoji: "🍌" },
  { key: "berries", emoji: "🍓" },
  { key: "citrus", emoji: "🍊" },
  { key: "lemon", emoji: "🍋" },
  { key: "mango", emoji: "🥭" },
  { key: "peach", emoji: "🍑" },
  { key: "pear", emoji: "🍐" },
  { key: "pineapple", emoji: "🍍" },
  { key: "coconut", emoji: "🥥" },
  { key: "grapes", emoji: "🍇" },
  { key: "watermelon", emoji: "🍉" },
  { key: "cherry", emoji: "🍒" },
  { key: "fig", emoji: "🫐" },
  { key: "dates", emoji: "🌴" },

  // ===== Dairy & Cheese =====
  { key: "cheese", emoji: "🧀" },
  { key: "cream", emoji: "🥛" },
  { key: "butter", emoji: "🧈" },
  { key: "yogurt", emoji: "🥛" },
  { key: "milk", emoji: "🥛" },
  { key: "mozzarella", emoji: "🧀" },
  { key: "parmesan", emoji: "🧀" },
  { key: "cheddar", emoji: "🧀" },
  { key: "feta", emoji: "🧀" },
  { key: "goat_cheese", emoji: "🐐" },
  { key: "cream_cheese", emoji: "🧀" },
  { key: "ricotta", emoji: "🧀" },
  { key: "blue_cheese", emoji: "🧀" },

  // ===== Dish Types =====
  { key: "soup", emoji: "🍲" },
  { key: "salad", emoji: "🥗" },
  { key: "curry", emoji: "🍛" },
  { key: "stew", emoji: "🥘" },
  { key: "stir_fry", emoji: "🍳" },
  { key: "wrap", emoji: "🌯" },
  { key: "pizza", emoji: "🍕" },
  { key: "burger", emoji: "🍔" },
  { key: "taco", emoji: "🌮" },
  { key: "sandwich", emoji: "🥪" },
  { key: "bowl", emoji: "🍱" },
  { key: "pie", emoji: "🥧" },
  { key: "casserole", emoji: "🫕" },
  { key: "risotto", emoji: "🍚" },
  { key: "sushi", emoji: "🍣" },
  { key: "bbq", emoji: "🔥" },
  { key: "roast", emoji: "🍖" },
  { key: "dumplings", emoji: "🥟" },
  { key: "spring_rolls", emoji: "🥡" },
  { key: "quesadilla", emoji: "🫓" },
  { key: "fajitas", emoji: "🌮" },
  { key: "paella", emoji: "🥘" },
  { key: "lasagna", emoji: "🍝" },
  { key: "ramen", emoji: "🍜" },
  { key: "pho", emoji: "🍜" },
  { key: "udon", emoji: "🍜" },
  { key: "pad_thai", emoji: "🍜" },
  { key: "fried_rice", emoji: "🍚" },
  { key: "omelette", emoji: "🍳" },
  { key: "frittata", emoji: "🍳" },
  { key: "quiche", emoji: "🥧" },
  { key: "shakshuka", emoji: "🍳" },
  { key: "pancakes", emoji: "🥞" },
  { key: "waffles", emoji: "🧇" },
  { key: "french_toast", emoji: "🍞" },
  { key: "porridge", emoji: "🥣" },
  { key: "granola", emoji: "🥣" },
  { key: "meatballs", emoji: "🧆" },
  { key: "kebab", emoji: "🍢" },
  { key: "satay", emoji: "🍢" },
  { key: "falafel", emoji: "🧆" },
  { key: "hummus", emoji: "🫘" },
  { key: "bruschetta", emoji: "🍞" },
  { key: "crostini", emoji: "🍞" },
  { key: "fondue", emoji: "🫕" },
  { key: "mac_and_cheese", emoji: "🧀" },
  { key: "carbonara", emoji: "🍝" },
  { key: "bolognese", emoji: "🍝" },
  { key: "poke_bowl", emoji: "🍱" },
  { key: "bibimbap", emoji: "🍚" },
  { key: "tacos_al_pastor", emoji: "🌮" },
  { key: "enchiladas", emoji: "🌮" },
  { key: "burritos", emoji: "🌯" },
  { key: "nachos", emoji: "🌮" },
  { key: "chili", emoji: "🌶️" },
  { key: "goulash", emoji: "🥘" },
  { key: "biryani", emoji: "🍚" },
  { key: "tikka_masala", emoji: "🍛" },
  { key: "butter_chicken", emoji: "🍛" },
  { key: "tandoori", emoji: "🍗" },

  // ===== Baked Goods & Desserts =====
  { key: "cake", emoji: "🎂" },
  { key: "cookies", emoji: "🍪" },
  { key: "brownies", emoji: "🍫" },
  { key: "muffins", emoji: "🧁" },
  { key: "cupcakes", emoji: "🧁" },
  { key: "cheesecake", emoji: "🍰" },
  { key: "tart", emoji: "🥧" },
  { key: "pastry", emoji: "🥐" },
  { key: "donut", emoji: "🍩" },
  { key: "ice_cream", emoji: "🍨" },
  { key: "pudding", emoji: "🍮" },
  { key: "mousse", emoji: "🍫" },
  { key: "tiramisu", emoji: "☕" },
  { key: "creme_brulee", emoji: "🍮" },
  { key: "panna_cotta", emoji: "🍮" },
  { key: "flan", emoji: "🍮" },
  { key: "sorbet", emoji: "🍧" },
  { key: "gelato", emoji: "🍨" },
  { key: "macarons", emoji: "🍪" },
  { key: "croissants", emoji: "🥐" },
  { key: "scones", emoji: "🧁" },
  { key: "banana_bread", emoji: "🍌" },
  { key: "cinnamon_rolls", emoji: "🥐" },
  { key: "chocolate", emoji: "🍫" },
  { key: "candy", emoji: "🍬" },
  { key: "fruit_salad", emoji: "🍓" },

  // ===== Drinks =====
  { key: "smoothie", emoji: "🥤" },
  { key: "juice", emoji: "🧃" },
  { key: "cocktail", emoji: "🍸" },
  { key: "mocktail", emoji: "🍹" },
  { key: "coffee", emoji: "☕" },
  { key: "tea", emoji: "🍵" },
  { key: "milkshake", emoji: "🥛" },
  { key: "lemonade", emoji: "🍋" },
  { key: "hot_chocolate", emoji: "☕" },
  { key: "wine_pairing", emoji: "🍷" },
  { key: "beer_pairing", emoji: "🍺" },
  { key: "sangria", emoji: "🍷" },
  { key: "punch", emoji: "🍹" },
  { key: "infused_water", emoji: "💧" },
  { key: "iced_coffee", emoji: "🧊" },
  { key: "chai", emoji: "🍵" },
  { key: "matcha", emoji: "🍵" },
  { key: "bubble_tea", emoji: "🧋" },

  // ===== Meal Type =====
  { key: "breakfast", emoji: "🌅" },
  { key: "brunch", emoji: "🥞" },
  { key: "lunch", emoji: "🥗" },
  { key: "dinner", emoji: "🍽️" },
  { key: "dessert", emoji: "🍰" },
  { key: "snack", emoji: "🥨" },
  { key: "appetizer", emoji: "🍢" },
  { key: "side_dish", emoji: "🥦" },
  { key: "drink", emoji: "🥤" },
  { key: "midnight_snack", emoji: "🌙" },
  { key: "light_meal", emoji: "🥗" },
  { key: "main_course", emoji: "🍽️" },

  // ===== Cooking Style =====
  { key: "quick_easy", emoji: "⚡" },
  { key: "one_pot", emoji: "🫕" },
  { key: "meal_prep", emoji: "📦" },
  { key: "batch_cooking", emoji: "🗓️" },
  { key: "slow_cooker", emoji: "⏰" },
  { key: "air_fryer", emoji: "💨" },
  { key: "grilled", emoji: "🔥" },
  { key: "baked", emoji: "🧁" },
  { key: "raw", emoji: "🥒" },
  { key: "no_cook", emoji: "❄️" },
  { key: "fried", emoji: "🍳" },
  { key: "deep_fried", emoji: "🍟" },
  { key: "steamed", emoji: "♨️" },
  { key: "smoked", emoji: "💨" },
  { key: "braised", emoji: "🥘" },
  { key: "poached", emoji: "🥚" },
  { key: "sauteed", emoji: "🍳" },
  { key: "roasted", emoji: "🍖" },
  { key: "blanched", emoji: "♨️" },
  { key: "marinated", emoji: "🫙" },
  { key: "fermented", emoji: "🫙" },
  { key: "pickled", emoji: "🥒" },
  { key: "instant_pot", emoji: "⏱️" },
  { key: "microwave", emoji: "📡" },
  { key: "sous_vide", emoji: "🌡️" },
  { key: "pressure_cooker", emoji: "⏱️" },
  { key: "wok", emoji: "🥡" },
  { key: "dutch_oven", emoji: "🫕" },
  { key: "cast_iron", emoji: "🍳" },
  { key: "sheet_pan", emoji: "🍳" },
  { key: "one_pan", emoji: "🍳" },

  // ===== Occasion & Lifestyle =====
  { key: "party_food", emoji: "🎉" },
  { key: "comfort_food", emoji: "🛋️" },
  { key: "budget_friendly", emoji: "💰" },
  { key: "kid_friendly", emoji: "👶" },
  { key: "date_night", emoji: "💕" },
  { key: "holiday", emoji: "🎄" },
  { key: "summer", emoji: "☀️" },
  { key: "winter", emoji: "❄️" },
  { key: "bbq_party", emoji: "🍗" },
  { key: "picnic", emoji: "🧺" },
  { key: "game_day", emoji: "🏈" },
  { key: "potluck", emoji: "🍲" },
  { key: "camping", emoji: "🏕️" },
  { key: "office_lunch", emoji: "💼" },
  { key: "romantic", emoji: "❤️" },
  { key: "family_dinner", emoji: "👨‍👩‍👧‍👦" },
  { key: "sunday_dinner", emoji: "🍖" },
  { key: "lazy_sunday", emoji: "😴" },
  { key: "movie_night", emoji: "🎬" },
  { key: "girls_night", emoji: "👯" },
  { key: "guys_night", emoji: "🍻" },
  { key: "baby_shower", emoji: "👶" },
  { key: "wedding", emoji: "💒" },
  { key: "birthday", emoji: "🎂" },
  { key: "graduation", emoji: "🎓" },
  { key: "new_years", emoji: "🎆" },
  { key: "christmas", emoji: "🎄" },
  { key: "thanksgiving", emoji: "🦃" },
  { key: "easter", emoji: "🐰" },
  { key: "halloween", emoji: "🎃" },
  { key: "valentines", emoji: "💝" },
  { key: "mothers_day", emoji: "💐" },
  { key: "fathers_day", emoji: "👔" },
  { key: "spring", emoji: "🌸" },
  { key: "fall", emoji: "🍂" },
  { key: "rainy_day", emoji: "🌧️" },
  { key: "snow_day", emoji: "⛄" },

  // ===== Flavor Profile =====
  { key: "spicy", emoji: "🌶️" },
  { key: "sweet", emoji: "🍯" },
  { key: "savory", emoji: "🧂" },
  { key: "sour", emoji: "🍋" },
  { key: "umami", emoji: "🍄" },
  { key: "smoky", emoji: "💨" },
  { key: "tangy", emoji: "🍋" },
  { key: "bitter", emoji: "☕" },
  { key: "mild", emoji: "😌" },
  { key: "hot", emoji: "🔥" },
  { key: "zesty", emoji: "✨" },
  { key: "rich", emoji: "🍫" },
  { key: "light", emoji: "🪶" },
  { key: "creamy", emoji: "🥛" },
  { key: "crispy", emoji: "🥓" },
  { key: "crunchy", emoji: "🥜" },
  { key: "tender", emoji: "🍖" },
  { key: "chewy", emoji: "🍬" },
  { key: "flaky", emoji: "🥐" },
  { key: "garlicky", emoji: "🧄" },
  { key: "herby", emoji: "🌿" },
  { key: "citrusy", emoji: "🍊" },
  { key: "nutty", emoji: "🥜" },
  { key: "earthy", emoji: "🍄" },
  { key: "fresh", emoji: "🌱" },
  { key: "aromatic", emoji: "👃" },

  // ===== Sauces & Condiments =====
  { key: "tomato_sauce", emoji: "🍅" },
  { key: "cream_sauce", emoji: "🥛" },
  { key: "pesto", emoji: "🌿" },
  { key: "gravy", emoji: "🥄" },
  { key: "salsa", emoji: "🍅" },
  { key: "guacamole", emoji: "🥑" },
  { key: "soy_sauce", emoji: "🥢" },
  { key: "teriyaki", emoji: "🥢" },
  { key: "bbq_sauce", emoji: "🍖" },
  { key: "hot_sauce", emoji: "🌶️" },
  { key: "mayo", emoji: "🥚" },
  { key: "mustard", emoji: "🟡" },
  { key: "vinaigrette", emoji: "🫒" },
  { key: "tahini", emoji: "🫘" },
  { key: "chimichurri", emoji: "🌿" },
  { key: "aioli", emoji: "🧄" },
  { key: "tzatziki", emoji: "🥒" },
  { key: "sriracha", emoji: "🌶️" },
  { key: "curry_sauce", emoji: "🍛" },
  { key: "coconut_milk", emoji: "🥥" },

  // ===== World Cuisines =====
  { key: "italian", emoji: "🇮🇹" },
  { key: "mexican", emoji: "🇲🇽" },
  { key: "asian", emoji: "🥢" },
  { key: "indian", emoji: "🇮🇳" },
  { key: "mediterranean", emoji: "🫒" },
  { key: "french", emoji: "🇫🇷" },
  { key: "thai", emoji: "🇹🇭" },
  { key: "japanese", emoji: "🇯🇵" },
  { key: "chinese", emoji: "🇨🇳" },
  { key: "korean", emoji: "🇰🇷" },
  { key: "greek", emoji: "🇬🇷" },
  { key: "middle_eastern", emoji: "🧆" },
  { key: "american", emoji: "🇺🇸" },
  { key: "spanish", emoji: "🇪🇸" },
  { key: "vietnamese", emoji: "🇻🇳" },
  { key: "dutch", emoji: "🇳🇱" },
  { key: "german", emoji: "🇩🇪" },
  { key: "british", emoji: "🇬🇧" },
  { key: "irish", emoji: "🇮🇪" },
  { key: "turkish", emoji: "🇹🇷" },
  { key: "moroccan", emoji: "🇲🇦" },
  { key: "ethiopian", emoji: "🇪🇹" },
  { key: "lebanese", emoji: "🇱🇧" },
  { key: "persian", emoji: "🇮🇷" },
  { key: "indonesian", emoji: "🇮🇩" },
  { key: "malaysian", emoji: "🇲🇾" },
  { key: "filipino", emoji: "🇵🇭" },
  { key: "brazilian", emoji: "🇧🇷" },
  { key: "peruvian", emoji: "🇵🇪" },
  { key: "argentinian", emoji: "🇦🇷" },
  { key: "cuban", emoji: "🇨🇺" },
  { key: "caribbean", emoji: "🏝️" },
  { key: "jamaican", emoji: "🇯🇲" },
  { key: "cajun", emoji: "🌶️" },
  { key: "creole", emoji: "🦐" },
  { key: "southern", emoji: "🍗" },
  { key: "tex_mex", emoji: "🌮" },
  { key: "hawaiian", emoji: "🌺" },
  { key: "scandinavian", emoji: "🇸🇪" },
  { key: "polish", emoji: "🇵🇱" },
  { key: "russian", emoji: "🇷🇺" },
  { key: "ukrainian", emoji: "🇺🇦" },
  { key: "hungarian", emoji: "🇭🇺" },
  { key: "belgian", emoji: "🇧🇪" },
  { key: "swiss", emoji: "🇨🇭" },
  { key: "portuguese", emoji: "🇵🇹" },
  { key: "australian", emoji: "🇦🇺" },
  { key: "african", emoji: "🌍" },
  { key: "fusion", emoji: "🌐" },
  { key: "street_food", emoji: "🛒" },
] as const;

export type OfficialTagKey = typeof OFFICIAL_TAGS[number]["key"];

export function isOfficialTag(tagKey: string): tagKey is OfficialTagKey {
  return OFFICIAL_TAGS.some(tag => tag.key === tagKey);
}

export function getOfficialTagEmoji(tagKey: string): string | undefined {
  const tag = OFFICIAL_TAGS.find(t => t.key === tagKey);
  return tag?.emoji;
}

// Helper to get tags by category for UI organization
export const TAG_CATEGORIES = {
  diet: ["vegan", "vegetarian", "gluten_free", "dairy_free", "low_carb", "keto", "high_protein", "paleo", "sugar_free", "healthy", "low_fat", "whole30", "low_sodium", "high_fiber", "low_calorie", "fodmap", "nut_free", "egg_free", "soy_free", "halal", "kosher"],
  protein: ["chicken", "beef", "pork", "lamb", "fish", "seafood", "turkey", "duck", "eggs", "tofu", "legumes", "salmon", "tuna", "shrimp", "crab", "lobster", "mussels", "bacon", "sausage", "ground_meat", "steak", "tempeh", "seitan", "game", "rabbit"],
  carbs: ["pasta", "rice", "potato", "noodles", "bread", "quinoa", "couscous", "sweet_potato", "oats", "polenta", "bulgur", "barley", "farro", "gnocchi", "tortilla", "pita", "naan", "croissant", "bagel"],
  vegetables: ["mushroom", "tomato", "onion", "garlic", "pepper", "carrot", "broccoli", "spinach", "zucchini", "eggplant", "cauliflower", "cabbage", "corn", "pumpkin", "squash", "asparagus", "avocado", "cucumber", "kale", "beets", "leek", "celery"],
  fruits: ["apple", "banana", "berries", "citrus", "lemon", "mango", "peach", "pear", "pineapple", "coconut", "grapes", "watermelon", "cherry", "fig", "dates"],
  dairy: ["cheese", "cream", "butter", "yogurt", "milk", "mozzarella", "parmesan", "cheddar", "feta", "goat_cheese", "cream_cheese", "ricotta", "blue_cheese"],
  dish_type: ["soup", "salad", "curry", "stew", "stir_fry", "wrap", "pizza", "burger", "taco", "sandwich", "bowl", "pie", "casserole", "risotto", "sushi", "bbq", "roast", "dumplings", "spring_rolls", "quesadilla", "fajitas", "paella", "lasagna", "ramen", "pho", "udon", "pad_thai", "fried_rice", "omelette", "frittata", "quiche", "shakshuka", "pancakes", "waffles", "french_toast", "porridge", "granola", "meatballs", "kebab", "satay", "falafel", "hummus", "bruschetta", "crostini", "fondue", "mac_and_cheese", "carbonara", "bolognese", "poke_bowl", "bibimbap", "tacos_al_pastor", "enchiladas", "burritos", "nachos", "chili", "goulash", "biryani", "tikka_masala", "butter_chicken", "tandoori"],
  baked_goods: ["cake", "cookies", "brownies", "muffins", "cupcakes", "cheesecake", "tart", "pastry", "donut", "ice_cream", "pudding", "mousse", "tiramisu", "creme_brulee", "panna_cotta", "flan", "sorbet", "gelato", "macarons", "croissants", "scones", "banana_bread", "cinnamon_rolls", "chocolate", "candy", "fruit_salad"],
  drinks: ["smoothie", "juice", "cocktail", "mocktail", "coffee", "tea", "milkshake", "lemonade", "hot_chocolate", "wine_pairing", "beer_pairing", "sangria", "punch", "infused_water", "iced_coffee", "chai", "matcha", "bubble_tea"],
  meal_type: ["breakfast", "brunch", "lunch", "dinner", "dessert", "snack", "appetizer", "side_dish", "drink", "midnight_snack", "light_meal", "main_course"],
  cooking_style: ["quick_easy", "one_pot", "meal_prep", "batch_cooking", "slow_cooker", "air_fryer", "grilled", "baked", "raw", "no_cook", "fried", "deep_fried", "steamed", "smoked", "braised", "poached", "sauteed", "roasted", "blanched", "marinated", "fermented", "pickled", "instant_pot", "microwave", "sous_vide", "pressure_cooker", "wok", "dutch_oven", "cast_iron", "sheet_pan", "one_pan"],
  occasion: ["party_food", "comfort_food", "budget_friendly", "kid_friendly", "date_night", "holiday", "summer", "winter", "bbq_party", "picnic", "game_day", "potluck", "camping", "office_lunch", "romantic", "family_dinner", "sunday_dinner", "lazy_sunday", "movie_night", "girls_night", "guys_night", "baby_shower", "wedding", "birthday", "graduation", "new_years", "christmas", "thanksgiving", "easter", "halloween", "valentines", "mothers_day", "fathers_day", "spring", "fall", "rainy_day", "snow_day"],
  flavor: ["spicy", "sweet", "savory", "sour", "umami", "smoky", "tangy", "bitter", "mild", "hot", "zesty", "rich", "light", "creamy", "crispy", "crunchy", "tender", "chewy", "flaky", "garlicky", "herby", "citrusy", "nutty", "earthy", "fresh", "aromatic"],
  sauces: ["tomato_sauce", "cream_sauce", "pesto", "gravy", "salsa", "guacamole", "soy_sauce", "teriyaki", "bbq_sauce", "hot_sauce", "mayo", "mustard", "vinaigrette", "tahini", "chimichurri", "aioli", "tzatziki", "sriracha", "curry_sauce", "coconut_milk"],
  cuisine: ["italian", "mexican", "asian", "indian", "mediterranean", "french", "thai", "japanese", "chinese", "korean", "greek", "middle_eastern", "american", "spanish", "vietnamese", "dutch", "german", "british", "irish", "turkish", "moroccan", "ethiopian", "lebanese", "persian", "indonesian", "malaysian", "filipino", "brazilian", "peruvian", "argentinian", "cuban", "caribbean", "jamaican", "cajun", "creole", "southern", "tex_mex", "hawaiian", "scandinavian", "polish", "russian", "ukrainian", "hungarian", "belgian", "swiss", "portuguese", "australian", "african", "fusion", "street_food"],
} as const;
